### ISSUE TITLE
EN template cannot be imported

### ISSUE THREAD

**Issue by realscorp** [romainsi/zabbix-VEEAM_B-R_jobs_trapper#1]
Hello.
Template in English cannot be imported. Once I select **TemplateVEEAM-BACKUPtrapper-eng.xml** and press Import button in Zabbix interface I get an error:
_Import failed
    Cannot read XML: (4) Start tag expected, '<' not found [Line: 1 | Column: 1]._
I've tried in Opera, Firefox and IE browsers with same results.
But French language template **TemplateVEEAM-BACKUPtrapperFR.xml** imports without any problem.

Zabbix version 3.4.6 on Debian 9.3

**Comment by realscorp** [comment]
I've just realized that EN template have '+' signs at the beginning of every line. After pluses removal import was succesful.

**Comment by romainsi** [comment]
Hi,

It's a mistake ^^ I've corrige the template.
Thx.
