### ISSUE TITLE
Template Link Error

### ISSUE THREAD

**Issue by brhunt1958** [romainsi/zabbix-VEEAM_B-R_jobs_trapper#10]
Hello Romain,

When I tried to link the template to our Veeam server, I received an error:
Item prototype "service.info[{#SERVICE.NAME},state]" already exists on "HAServer", inherited from another template.

It looks as if it is conflicting with an item prototype on the Template OS Windows template?

The Veeam server has had the zabbix agent on it for a while now, just adding in this new functionality.

Thanks.

Bryan Hunt

**Comment by romainsi** [comment]
Hi,

The easiest way is to purge the "windows services" records and re-discover, if you have followed the prerequisites (add alias and modify regular expressions) Veeam services should no longer be discovered by the windows OS template but by the Veeam one.

It's also possible to untag the template with data purge and re-tag it but you lose history.

Regards,
Romain.

**Comment by brhunt1958** [comment]
Romain,

Thanks for the reply.

I tried to purge the windows service records, but wasn't quite sure what context to purge in so that did not work.

I unlinked the windows os template, linked in your Veeam template, then re-linked the os template.  All went well there.

I am getting results from the template/script, but they aren't quite working properly.  I have attached an image of the latest data screen.

A couple of questions please:
- All of the windows services are now lumped under the Veeam services heading.  Is this expected?  No problem either way, just want to be sure working correctly.
- On the latest data screen, several items are updating, several items are not.  As you can see, they show as a script timeout.  But, if the script was timing out, wouldn't we see that will all items?

Thanks for any direction that you can give.

Bryan Hunt



[Hardcopy.pdf](https://github.com/romainsi/zabbix-VEEAM_B-R_jobs_trapper/files/2202763/Hardcopy.pdf)

**Comment by romainsi** [comment]
Hi Bryan,

For Veeam Services it's the same item (service.info) like use your template 'Windows OS template' so no problems to work correctly :) 

Having Windows and Veeam services in the'veeam services' header is an oversight on your part I things (cf pj):
```
In Zabbix : Administration, General, Regular Expression : Add a new regular expression :
Name : "Veeam" ; Expression type : "TRUE" ; Expression : "Veeam.*"
And modify regular expression "Windows service startup states for discovery" : Add : 
Name : "Veeam" ; Expression type : "FALSE" ; Expression : "Veeam.*"

```
![image](https://user-images.githubusercontent.com/30522413/42839727-e47a9cae-8a04-11e8-8c18-f4dbf3ee1c97.png)

Your datascreen is strange ... the query for retrieve free space and total space are wmi request look in the code (you can try replacing "$ID" with ID of your repository)  : 

```
"RepoCapacity" {
  $query = Get-WmiObject -Class Repository -ComputerName $env:COMPUTERNAME -Namespace ROOT\VeeamBS | Where-Object {$_.Name -eq "$ID"}
  $query|Select-Object -ExpandProperty Capacity
    }
    "RepoFree" {
  $query = Get-WmiObject -Class Repository -ComputerName $env:COMPUTERNAME -Namespace ROOT\VeeamBS | Where-Object {$_.Name -eq "$ID"}
  $query|Select-Object -ExpandProperty FreeSpace
    }
```

If you're working on a VM may be thinking about increasing performance ?
Otherwise the repository is still present in veeam b&r ?
