### ISSUE TITLE
Error adding to the Host

### ISSUE THREAD

**Issue by hyprem** [romainsi/zabbix-VEEAM_B-R_jobs_trapper#11]
Get an error when assign Template to my Host:
item prototype "service.info[{#SERVICE.NAME},state]" already exists on "IFA-WIN12R2", inherited from another template.

Activated Template: OS Windows and Veeam Backup Trapper.

Any suggestions

**Comment by romainsi** [comment]
Hi,

The veeam services were already discovered by the service discovery model of the windows OS template.

First : In your host, delete and PURGE (purge is very important) your template windows OS.
Second : In Zabbix : Administration, General, Regular Expression : modify regular expression "Windows service startup states for discovery" :
Add :
Name : "Veeam" ; Expression type : "FALSE" ; Expression : "Veeam.*"

Then, you can import Veeam Template, and re-link your template Windows OS and Veeam to your Host.

You can also delete the service.discovery key in the Windows OS template if you do not use it (but don't forget to purge model in your host !)
