### ISSUE TITLE
Powershell script takes long time to finish for some items

### ISSUE THREAD

**Issue by STAV550** [romainsi/zabbix-VEEAM_B-R_jobs_trapper#14]
Hello Romain,

I use your script and template to monitor my veeam backup server. I have noticed for some items, the powershell script takes long time to finish. I have tested localy   and remotely the script and for two items, the script exceeds zabbix agent timeout (I have set the maximum timeout value in my agent config and server config which is 30). All other items run correctly.

The concerned items are :

Result.[{#JOBID}]
vbr[Result,{#JOBID}]

Please see the results below

![zabbix issue](https://user-images.githubusercontent.com/42958487/45017223-5751ec80-b027-11e8-9f26-db775245c1ce.PNG)

PS C:\Program Files\Zabbix Agent\scripts> .\zabbix_vbr_job.ps1 Result 5267df7f-81ad-454e-957c-6772b8dee33c
Import-Clixml : Fin de fichier inattendue. Les éléments suivants ne sont pas fermés : Props, Obj, Objs. Ligne 8489778,
position 8.
Au caractère C:\Program Files\Zabbix Agent\scripts\zabbix_vbr_job.ps1:141 : 10
+   $xml = Import-Clixml "$pathxml\backupsession.xml"
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Clixml], XmlException
    + FullyQualifiedErrorId : System.Xml.XmlException,Microsoft.PowerShell.Commands.ImportClixmlCommand

Execution reussie

[admin@zabbix ~]$ zabbix_get -s 192.168.0.191 -k vbr[Result,5267df7f-81ad-454e-957c-6772b8dee33c]
ZBX_NOTSUPPORTED: Timeout while executing a shell script.

The script execution time for these two items are around 40 seconds.

For example, the command below runs correctly

[admin@zabbix ~]$ zabbix_get -s 192.168.0.191 -k vbr[NextRunTime,5267df7f-81ad-454e-957c-6772b8dee33c]
1536033616

I hope I was clear on this ^^

Thanks for any help !

**Comment by romainsi** [comment]
Hi,

Can you verify if yours XML is created and existing in your zabbix scripts folder ?
Verify your variable $pathxml is correct too.

**Comment by romainsi** [comment]
Peux tu essayer d'importer manuellement un des fichiers xml dans Powershell et voir s'il retourne la même erreur :

`$pathxml = 'C:\Program Files\Zabbix Agent\scripts'
Import-Clixml "$pathxml\backupjob.xml"`

**Comment by MairieStAv** [comment]
Avec backupjob.xml, je n'ai pas d'erreur d'exécution et j'ai beaucoup d'infos qui remontent correctement.

**Comment by romainsi** [comment]
hum ... peux tu refaire un test d'import xml powershell avec backupsession.xml et renvoyer le code d'erreur s'il y en a un ?

**Comment by STAV550** [comment]
Avec backupsession.xml, j'ai bien l'historique de mes backup mais pas d'erreur lors de l'exécution. Ce fichier a une taille de 1 Go et prends du temps à se terminer.

**Comment by romainsi** [comment]
1Go effectivement c'est beaucoup.
Peux tu dans un 1er temps réduire le nombre de log Veeam (cf lien : Changing Session history retention) et si cela ne suffis pas voir la manip SQL (Clear old job sessions) :

https://www.veeam.com/kb1995

**Comment by STAV550** [comment]
Effectivement en réduisant le nombre de log, le fichier est beaucoup plus petit (21 Mo) et le script fonctionne correctement maintenant.

Merci de votre aide :)
