### ISSUE TITLE
Global regular expression "Veeam" does not exist.

### ISSUE THREAD

**Issue by realscorp** [romainsi/zabbix-VEEAM_B-R_jobs_trapper#2]
When adding a Veeam host and applying a template discovery rule "VEEAM Services" becomes broken with an error **"Global regular expression "Veeam" does not exist."**
Looks like there should be a "^Veeam" instead of "@Veeam" in a rule filter condition. After I replaced this value with a right one discovery rule start to work fine.

**Comment by romainsi** [comment]
Ok I've modify the template ;) Thx
