### ISSUE TITLE
Veeam jobs modification

### ISSUE THREAD

**Issue by lduriez** [romainsi/zabbix-VEEAM_B-R_jobs_trapper#3]
Hi,

Thanks for your template, it works great.

The only problem I have is how do you manage when you modify or delete a veeam job? Because when I do that I have issue in zabbix about the jobs modify or delete.

Do you think it's possible to manage, in the discovery, the delete of items that doesn't exist anymore or that are modified?

Thanks

Luc

**Comment by romainsi** [comment]
Hi Luc,
The discovery process of Zabbix remove Jobs that is not present (delete or rename) automatically after Ndays.
Look the screen capture for option (sorry the interface is in french) : retention period for lost values
![image](https://user-images.githubusercontent.com/30522413/36194784-684736ae-116b-11e8-8817-ad8f75c7c53f.png)

**Comment by lduriez** [comment]
Thanks, didn't notice this before xD
