### ISSUE TITLE
Job Agent not discovered

### ISSUE THREAD

**Issue by cmbcbe** [romainsi/zabbix-VEEAM_B-R_jobs_trapper#4]
Hello,

thanks for this great script.
Could it be possible to add discovery for Veeam Endpoint Backup Job (agent)???
https://helpcenter.veeam.com/docs/backup/powershell/get-vbrepjob.html?ver=95

Based on Get-VBREPJob

Thanks you :)

**Comment by romainsi** [comment]
I'm working on it :)

**Comment by romainsi** [comment]
It's done ;)

**Comment by cmbcbe** [comment]
Thank you very much, i will try it!
