### ISSUE TITLE
Cannot Link template

### ISSUE THREAD

**Issue by MikeW83** [romainsi/zabbix-VEEAM_B-R_jobs_trapper#5]
Hello,

I have added the template as described in your documentation, but I receive this error:

> Item prototype "service.info[{#SERVICE.NAME},state]" already exists on "BACKUPSERVER", inherited from another template.

I have also linked the default template for Windows OS with this Host. What I'm doing wrong?

Thank you!
Regards, Michael

**Comment by romainsi** [comment]
Hi,

It's normal, it's a mistake ...
The veeam services were already discovered by the service discovery model of the windows OS template.

First : In your host, delete and PURGE (purge is very important) your template windows OS.
Second : In Zabbix : Administration, General, Regular Expression : modify regular expression "Windows service startup states for discovery" :
Add :
Name : "Veeam" ; Expression type : "FALSE" ; Expression : "Veeam.*"

![image](https://user-images.githubusercontent.com/30522413/40770646-95e34b7c-64bb-11e8-9cca-ab2848afd504.png)

Then, you can import Veeam Template, and re-link your template Windows OS and Veeam to your Host. 

You can also delete the service.discovery key in the Windows OS template if you do not use it (but don't forget to purge model in your host !)
