### ISSUE TITLE
Error - Zabbix Sender

### ISSUE THREAD

**Issue by rcaldas88** [romainsi/zabbix-VEEAM_B-R_jobs_trapper#6]
I have a problem with zabbixsender and I cant solve it. Can you help me?

This is my Zabbix Agent Conf file on VeeamServer:

Server=IP
Hostname=PRDVEEAMBKP
LogFile=C:\Program Files\Zabbix Agent\log.txt
StartAgents=3
Timeout=30
DebugLevel=5
EnableRemoteCommands=1
LogRemoteCommands=1
UnsafeUserParameters=1
Alias=service.discovery.veeam:service.discovery
UserParameter=vbr[*],powershell -NoProfile -ExecutionPolicy Bypass -File "C:\Program Files\Zabbix Agent\scripts\zabbix_vbr_job.ps1" "$1" "$2"
ServerActive=IP:10051

And this is the powershell result:
PS C:\Program Files\Zabbix Agent\scripts> .\zabbix_vbr_job.ps1 exportxml
Command Send

PS C:\Program Files\Zabbix Agent\scripts> .\zabbix_vbr_job.ps1 discovery
{"data":[{"{#JOBID}":"000c68c7-0299-4b3f-afa0-e6a58f59215a","{#JOBNAME}":"WINDOWS_BACKUP_QLTSPCLOUD","{#JOBSCHEDULED}":"
True"},{"{#JOBID}":"bdba3b4e-55b4-40f9-a84f-fdff4c60fd12","{#JOBNAME}":"LINUX_BACKUP_QLTSPCLOUD","{#JOBSCHEDULED}":"True
"}]}

PS C:\Program Files\Zabbix Agent\scripts> cd ..

PS C:\Program Files\Zabbix Agent> .\zabbix_sender.exe -c .\zabbix_agentd.conf -k Result.[000c68c7-0299-4b3f-afa0-e6a58f5
9215a] -o 2 -vv
zabbix_sender.exe [3480]: DEBUG: answer [{"response":"success","info":"processed: 0; failed: 1; total: 1; seconds spent:
0.000026"}]
info from server: "processed: 0; failed: 1; total: 1; seconds spent: 0.000026"
sent: 1; skipped: 0; total: 1

Can you help me?

**Comment by romainsi** [comment]
Hi,

You've a problem with Zabbix Sender.

Try this (without double 'v' at end) :
.\zabbix_sender.exe -c .\zabbix_agentd.conf -k Result.[000c68c7-0299-4b3f-afa0-e6a58f59215a] -o 2 -v

If not work try :
.\zabbix_sender.exe -z "ZABBIX-IP" -s PRDVEEAMBKP -k Result.[000c68c7-0299-4b3f-afa0-e6a58f59215a] -o 2 -v

If 2sd work, you've a problem with your Zabbix Agent Conf.

**Comment by rcaldas88** [comment]
Hi, Romain.

That's my zabbix.agentd.conf:

```
Server=IP
ServerActive=IP:10051
Hostname=PRDVEEAMBKP
LogFile=C:\Program Files\Zabbix Agent\log.txt
StartAgents=3
Timeout=30
DebugLevel=5
EnableRemoteCommands=1
LogRemoteCommands=1
UnsafeUserParameters=1
Alias=service.discovery.veeam:service.discovery
UserParameter=vbr[*],powershell -NoProfile -ExecutionPolicy Bypass -File "C:\Program Files\Zabbix Agent\scripts\zabbix_vbr_job.ps1" "$1" "$2"
```

I did the two commands that you sent and obtained the following errors:

**1st command;**
```
PS C:\Program Files\Zabbix Agent>  .\zabbix_sender.exe -c .\zabbix_agentd.conf -k Result.[000c68c7-0299-4b3f-afa0-e6a58f
59215a] -o 2 -v
info from server: "processed: 0; failed: 1; total: 1; seconds spent: 0.000031"
sent: 1; skipped: 0; total: 1
PS C:\Program Files\Zabbix Agent>
info from server: "processed: 0; failed: 1; total: 1; seconds spent: 0.000031"
sent: 1; skipped: 0; total: 1
```

**2sd command:**
```
PS C:\Program Files\Zabbix Agent>  .\zabbix_sender.exe -z 9.1.1.96 -s PRDVEEAMBKP -k Result.[000c68c7-0299-4b3f-afa0-e6a
58f59215a] -o 2 -v
info from server: "processed: 0; failed: 1; total: 1; seconds spent: 0.000027"
sent: 1; skipped: 0; total: 1
```
Is there something to be modified on Zabbix Server (zabbix_server.conf)?

**Comment by romainsi** [comment]
Hi,

Can you verify if item "Result.[000c68c7-0299-4b3f-afa0-e6a58f59215a]" is not missing in zabbix server ?

Verify you can ping your zabbix server Ip and NetbiosName (or dns name) and port 10050 & 10051 is open (telnet "IpZabbixServer" 10050). If not open verify iptables or firewalld.

Check that there is at least 1 Process Zabbix Trapper listening on your server :
In your zabbix_server.conf :
StartTrappers   => Number of pre-forked instances of trappers.
Trappers accept incoming connections from Zabbix sender, active agents and active proxies.
At least one trapper process must be running to display server availability and view queue in the frontend.

**Comment by rcaldas88** [comment]
Hi,

I'll answer you under your questions:

**Can you verify if item "Result.[000c68c7-0299-4b3f-afa0-e6a58f59215a]" is not missing in zabbix server ?**
No, its not created. Only the discoveries of VEEAM Services and VEEAM Repository appeared on the Zabbix Server. At the end of the text I put a picture of Latest Data of the Veeam Server.

**Verify you can ping your zabbix server Ip and NetbiosName (or dns name) and port 10050 & 10051 is open (telnet "IpZabbixServer" 10050). If not open verify iptables or firewalld.**
It's all right about that. I can connect to both ports you have informed and ping IP and Zabbix Server NETBIOS.

**Check that there is at least 1 Process Zabbix Trapper listening on your server :
In your zabbix_server.conf :
StartTrappers => Number of pre-forked instances of trappers.
Trappers accept incoming connections from Zabbix sender, active agents and active proxies.
At least one trapper process must be running to display server availability and view queue in the frontend.**
Everything OK with that too.

[root@qcontrol zabbix]# cat zabbix_server.conf | grep StartTrappers
#Option: StartTrappers
StartTrappers=5

I did some tests with some functions, but using keys with systemrun [powershell] and got success manually:

![image](https://user-images.githubusercontent.com/19288134/40851748-b2cd8516-659e-11e8-898b-03ebcf999d39.png)

**Comment by rcaldas88** [comment]
Another important point:

PS C:\Program Files\Zabbix Agent\scripts> .\zabbix_vbr_job.ps1 Result 000c68c7-0299-4b3f-afa0-e6a58f59215a
Execution non reussie
PS C:\Program Files\Zabbix Agent>

**Comment by romainsi** [comment]
Hi,

The error in your last post is normal because zabbix_sender failed.

Can you check if the template is imported correctly because you should have in the "Veeam jobs" discovery rule a "zabbix trapper element prototype" that should appear like this: Result[{JOBID}]  

If the trapper element is not present it's normal that zabbix trapper returns an error.
Look at the screenshots (sorry french template ...)

In template :
![image](https://user-images.githubusercontent.com/30522413/40885138-e4fa7a16-6720-11e8-9acf-4c7e5603830c.png)

In last data server : 
![image](https://user-images.githubusercontent.com/30522413/40885152-39cff4bc-6721-11e8-9d54-f24f1fb48b27.png)

**Comment by rcaldas88** [comment]
Hi,

No problem about the french, Romain. You're helping me a lot, thanks for that. About the problem, the item in VEEAM jobs is created, as you demonstrated in the image. I noticed that the problem is only in items that depend of Zabbix Trapper.  All other Zabbix Agent items are working correctly.

Is there any way to do another test?

![image](https://user-images.githubusercontent.com/19288134/40918769-aa7198b2-67dd-11e8-8188-049d534a55bb.png)

**Comment by rcaldas88** [comment]
To improve our analysis, below is the Zabbix Server log:

 4759:20180604:030806.380 Zabbix agent item "vbr["DiscoveryTape"]" on host "PRDVEEAMBKP" failed: another network error, wait for 15 seconds
  4759:20180604:030825.389 Zabbix agent item "vbr["Discovery"]" on host "PRDVEEAMBKP" failed: first network error, wait for 15 seconds

**Comment by romainsi** [comment]
Hum ... very strange ^^ 

It would be more of a discovery problem.
Your item discovery result it's activated ?

On your zabbix server item discovery is correct ?
zabbix_get -s PRDVEEAMBKP -k 'vbr["Discovery"]'
Must return a JSON value.

What is your version of Zabbix Server, Agent? The version of Veeam B&R? The version of Windows Server used ?
How many backup have you on the B&R ?

Can you try increasing the number of agents on the zabbix agent ?
In your zabbix_agentd.conf : StartAgents='X' (try with 6 ou 10).

Last resort, you can manually create the item zabbix trapper on the server :
On the host : 
Add new item Zabbix_trapper with an example name and add key :
vbr[Result,000c68c7-0299-4b3f-afa0-e6a58f59215a]  replace with your own JOBID

The zabbix_trapper should be able to receive the information after its.

**Comment by romainsi** [comment]
To get a result the Get-VBRJob command is based on the history.
Did you run the backup jobs ?
I think that's the problem ^^

For Low-level discovery your JSON 
`{"data":[{"{#JOBID}":"000c68c7-0299-4b3f-afa0-e6a58f59215a","{#JOBNAME}":"WINDOWS_BACKUP_QLTSPCLOUD","{#JOBSCHEDULED}":"True"},{"{#JOBID}":"bdba3b4e-55b4-40f9-a84f-fdff4c60fd12","{#JOBNAME}":"LINUX_BACKUP_QLTSPCLOUD","{#JOBSCHEDULED}":"True"}]}`
is correct.

Look in the template if the trapper element is enabled :
![image](https://user-images.githubusercontent.com/30522413/40940511-59511fe6-6848-11e8-899f-6f30c5315e15.png)

**Comment by rcaldas88** [comment]
HI,

All the backups jobs are scheduled to run every hour, all the backups is running succeed

**Comment by rcaldas88** [comment]
Hi,

I finally resolve the problem and all jobs are showing up, but shellscript execution freezes after a while. The backupsessiontemp.xml file stops at 0kb and no longer loads any information.

Any idea?

**Comment by rcaldas88** [comment]
Hi,

Everything OK here! Thanks, the template is awesome!

Regards!
