### ISSUE TITLE
VEEAM Backup & Recovery job(s) - Excluded size - issue

### ISSUE THREAD

**Issue by cmbcbe** [romainsi/zabbix-VEEAM_B-R_jobs_trapper#8]
Hello,

it seems that the last script is unable to retrieve exluded size from job with this error:

```
Value "Import-Clixml : Impossible de trouver le fichier 'C:\Program Files\Zabbix 
Agent\scripts\backupjob.xml'.
Au caract" of type "string" is not suitable for value type "Numeric (unsigned)"
```
Any ideas? Thanks you

**Comment by cmbcbe** [comment]
The file 'C:\Program Files\Zabbix 
Agent\scripts\backupjob.xml' exist and is readable....

**Comment by cmbcbe** [comment]
Sorry, i have forgot to modify the template since i work in active mode. So i have change the item to zabbix agent actif and it's OK sorry :)

**Comment by romainsi** [comment]
Can you give me the item concerned that I update it for the others ?

**Comment by cmbcbe** [comment]
this is not to modify widely, this is a customization of mine since i use all my template in active mode because my agent are on the net behind firewall...

**Comment by romainsi** [comment]
Ok ;)
