### ISSUE TITLE
veeam support says that the script kill our backups

### ISSUE THREAD

**Issue by andreaconsadoriw** [romainsi/zabbix-VEEAM_B-R_jobs_trapper#9]
Hi,
i had several issue with veeam backup and the support point out the problem was the zabbix_trapper powershell script:

build 9.5.0.1536

error given:
1-Failed to call RPC function 'FcCreateDir': Error code: 0x80070008. Cannot initialize COM runtime.
2-Error code: 0x80070583

Support says that we have to modify the script and enter "disconnect"

**Comment by romainsi** [comment]
Hi,

The function Backup & Support Point use Connect & Disconnect :

`$connectVeeam = Connect-VBRServer`
`$disconnectVeeam = Disconnect-VBRServer`

Have you more informations ?

**Comment by andreaconsadoriw** [comment]
by Veeam support:
As for our telephone conversation, the problem is caused by Veeam's satelites, which do not close correctly if Zabix scripts also run.
To try to solve the problem, we kindly ask you to follow the instructions below:
~~~~~~
     Modify PS script: add Connect-VBRServer and Disconnect-VBRServer The client must use this command to close PowerShell session and finish satellite process https% 3A% 2F% 2Fhelpcenter.veeam.com% 2Fdocs 2Fbackup%%% 2Fpowershell 2Fgetting_started.html% 3Fver% 3D95 & bfec4376 & e = h = 15,839,005 & f = n & p = y
     Restart Veeam server.
     Monitor server and satellite processes.
     If you still see multiple satellites - collect fresh logs and PS script for further investigation.

**Comment by romainsi** [comment]
I had already had this problem and I also noticed it in production but each Veeam request uses connect and disconnect in my script.

`    $connectVeeam = Connect-VBRServer
      $query = Get-VBRJob | Where-Object {$_.IsScheduleEnabled -eq "true"} | Select-Object Id,Name, IsScheduleEnabled
    $disconnectVeeam = Disconnect-VBRServer`

`    $connectVeeam = Connect-VBRServer
      $query = Get-VBRTapeJob | Select-Object Id,Name
    $disconnectVeeam = Disconnect-VBRServer`

etc ...

**Comment by andreaconsadoriw** [comment]
I used this script 3 months ago, was the change made later?

**Comment by romainsi** [comment]
ha ! I understand better ^^ 
I update the script regularly, feel free to update it too ;)

**Comment by andreaconsadoriw** [comment]
so you still have this problem in production?
i'm using your script but a 3 months old version, maybe you fix this problem in latest release

**Comment by romainsi** [comment]
I've problems with old script but the one published is correct.
